// Generated by scripts/generate-image-dimensions.mjs — do not edit by hand.
export const IMAGE_DIMENSIONS: Record<string, { width: number; height: number }> = {
  "/images/poster1.webp": {
    "width": 1200,
    "height": 664
  },
  "/images/poster11-1.webp": {
    "width": 560,
    "height": 418
  },
  "/images/poster11-2.webp": {
    "width": 123,
    "height": 173
  },
  "/images/poster11-3.webp": {
    "width": 706,
    "height": 742
  },
  "/images/poster12.webp": {
    "width": 1174,
    "height": 800
  },
  "/images/poster13.webp": {
    "width": 567,
    "height": 437
  },
  "/images/poster14.webp": {
    "width": 350,
    "height": 450
  },
  "/images/poster15.webp": {
    "width": 1200,
    "height": 868
  },
  "/images/poster17.webp": {
    "width": 1200,
    "height": 656
  },
  "/images/poster18.webp": {
    "width": 499,
    "height": 467
  },
  "/images/poster19.webp": {
    "width": 950,
    "height": 539
  },
  "/images/poster2.webp": {
    "width": 631,
    "height": 631
  },
  "/images/poster4.webp": {
    "width": 567,
    "height": 567
  },
  "/images/poster6.webp": {
    "width": 1200,
    "height": 2024
  },
  "/images/poster8.webp": {
    "width": 956,
    "height": 926
  },
  "/images/session2.webp": {
    "width": 1024,
    "height": 1024
  },
  "/images/session3.webp": {
    "width": 1080,
    "height": 1358
  },
  "/images/session4.webp": {
    "width": 818,
    "height": 776
  }
};
